plugins {
    id 'com.android.application'
}

android {
    namespace 'com.rushani.ask.latinpack'
    compileSdk 34

    defaultConfig {
        applicationId "com.rushani.ask.latinpack"
        minSdk 16
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
